### ISSUE TITLE
Create initial frontend application using Vite

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#1]
## Tasks 
- [x] Create initial vite frontend with https://vite.dev/guide/#scaffolding-your-first-vite-project
- [x] Frontend project will be in `frontend/` directory
- [x] Create `README.md` file
