### ISSUE TITLE
Add station search by music genre

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#39]
### Tasks
- [x] Watch UI design https://www.youtube.com/watch?v=qyomWr_C_jA
- [x] Watch "How to Scroll Horizontally in React JS - Styled With Tailwind CSS - Javascript" - https://www.youtube.com/watch?v=x4bom6Udk_4
- [x] Create list of genres that are common (e.g look at spotify genres or from looking at https://at1.api.radio-browser.info/json/tags?order=stationcount&reverse=true
- [x] Check that tags exists and have sufficient stations - e.g. search by `<filter>` http://at1.api.radio-browser.info/json/tags/<filter>

E.g. maybe similar design to youtube, where the different tags are listed in a row, with arrow at the side for scrolling
![image](https://github.com/user-attachments/assets/cecf051e-db85-4c8c-9dca-1769af496b35)

Example Spotify Music Genres - checking category under "Music" on Spotify App
Selected some common genres that are also present in Radio Browser API and have good amount of stations - https://at1.api.radio-browser.info/json/tags?order=stationcount&reverse=true&hidebroken=true

1) Get genres, filter down to common genres, sort by name. Create a new list of genres with key (genre) => list of strings representing the tags associated by radio browser for that genre
```javascript
import fs from "node:fs"

const data = JSON.parse(fs.readFileSync("genre.json", "utf-8"))

// https://www.freecodecamp.org/news/how-to-sort-array-of-objects-by-property-name-in-javascript/
const sortedByName = data.sort((a, b) => a.name.localeCompare(b.name))
console.log(sortedByName)
```

## Radio browser consolidated tags
```json
[
  {
    "name": "00's,00s,2000s",
    "stationcount": "23,144,225"
  },
  {
    "name": "2010s,10s",
    "stationcount": "83,24"
  },
  {
    "name": "1920s",
    "stationcount": 17
  },
  {
    "name": "1930s,30s",
    "stationcount": "21,11"
  },
  {
    "name": "1940s,40s",
    "stationcount": "25,12"
  },
  {
    "name": "50's,50s,1950s",
    "stationcount": "7,65,39"
  },
  {
    "name": "60's,60s,1960,1960s,sixties",
    "stationcount": "43,228,14,60,8"
  },
  {
    "name": "1970s,70,70's,70s,70s disco,70s rock,70s rock ballads,70s soft rock,70er",
    "stationcount": "88,10,90,504,27,5,4,11,66"
  },
  {
    "name": "80,80's,80s,80s radio,80er,80s rock,80s soft rock,1980's,1980s,1980s hits,#80s,eighties,the best of 80's",
    "stationcount": "27,201,1038,10,130,23,7,35,142,6,8,11,37"
  },
  {
    "name": "90's,90er,90s,90s alternative,90s dance,1990s,#90s,classic 90s",
    "stationcount": "143,84,812,5,16,99,8,7"
  },
  {
    "name": "20th century",
    "stationcount": 14
  },
  {
    "name": "8 bit,8bit",
    "stationcount": "7,5"
  },
  {
    "name": "abstract",
    "stationcount": 4
  },
  {
    "name": "acid",
    "stationcount": 8
  },
  {
    "name": "acoustic,acoustic guitar",
    "stationcount": "34,3"
  },
  {
    "name": "active rock",
    "stationcount": 34
  },
  {
    "name": "adult contemporary",
    "stationcount": 765
  },
  {
    "name": "adult hits",
    "stationcount": 120
  },
  {
    "name": "african music",
    "stationcount": 89
  },
  {
    "name": "afro,afro-pop,afrobeat,afrobeats,afro-latin music",
    "stationcount": "8,3,8,24,3"
  },
  {
    "name": "alt-folk",
    "stationcount": 3
  },
  {
    "name": "alternative,alternative rock,alternative / indie,alternative indie rock,alternative pop,alternative wave",
    "stationcount": "556,273,40,10,13,3"
  },
  {
    "name": "am",
    "stationcount": 165
  },
  {
    "name": "ambient,ambient electronic,ambient lounge,ambient and relaxation music",
    "stationcount": "270,1,6,79"
  },
  {
    "name": "americana",
    "stationcount": 43
  },
  {
    "name": "anarchism",
    "stationcount": 3
  },
  {
    "name": "anime,anime groove,anime openings,anime ost,anime radio,animegroove",
    "stationcount": "49,3,8,1,13,3"
  },
  {
    "name": "apm",
    "stationcount": 43
  },
  {
    "name": "art,arts",
    "stationcount": "7,31"
  },
  {
    "name": "art rock",
    "stationcount": 29
  },
  {
    "name": "asian,asian music",
    "stationcount": "7,3"
  },
  {
    "name": "atmospheric",
    "stationcount": 12
  },
  {
    "name": "atmospheric black metal",
    "stationcount": 3
  },
  {
    "name": "avant-garde",
    "stationcount": 28
  },
  {
    "name": "avant-garde jazz",
    "stationcount": 3
  },
  {
    "name": "bachata",
    "stationcount": 57
  },
  {
    "name": "balada,balada pop",
    "stationcount": "79,80"
  },
  {
    "name": "ballads",
    "stationcount": 57
  },
  {
    "name": "banda,banda tradicional",
    "stationcount": "245,72"
  },
  {
    "name": "bass",
    "stationcount": 25
  },
  {
    "name": "beijing",
    "stationcount": 8
  },
  {
    "name": "big band",
    "stationcount": 55
  },
  {
    "name": "blues",
    "stationcount": 262
  },
  {
    "name": "blues rock,bluesrock",
    "stationcount": "54,3"
  },
  {
    "name": "bollywood",
    "stationcount": 49
  },
  {
    "name": "brazilian music,brazilian pop",
    "stationcount": "52,11"
  },
  {
    "name": "breakbeat hardcore,breakcore,breakbeat",
    "stationcount": "4,3,23"
  },
  {
    "name": "business",
    "stationcount": 18
  },
  {
    "name": "calm",
    "stationcount": 12
  },
  {
    "name": "campus radio,cbs sports radio,student radio",
    "stationcount": "51,8,72"
  },
  {
    "name": "chamber",
    "stationcount": 8
  },
  {
    "name": "charts",
    "stationcount": 172
  },
  {
    "name": "children",
    "stationcount": 81
  },
  {
    "name": "chillout,chill,chill beats,chill house,chill-out,chillhop,chillout+lounge,chilled trap,chillstep",
    "stationcount": "342,133,6,11,2,8,45,6,6"
  },
  {
    "name": "cantonese",
    "stationcount": 3
  },
  {
    "name": "chinese,china,音乐",
    "stationcount": "13,2,7"
  },
  {
    "name": "chiptune",
    "stationcount": 18
  },
  {
    "name": "choir",
    "stationcount": 8
  },
  {
    "name": "christmas music",
    "stationcount": 170
  },
  {
    "name": "classics,classic",
    "stationcount": "115,141"
  },
  {
    "name": "classic alternative",
    "stationcount": 7
  },
  {
    "name": "classic blues",
    "stationcount": 8
  },
  {
    "name": "classic country",
    "stationcount": 57
  },
  {
    "name": "classic hip hop",
    "stationcount": 20
  },
  {
    "name": "classic hits",
    "stationcount": 835
  },
  {
    "name": "classic jazz",
    "stationcount": 41
  },
  {
    "name": "classic pop",
    "stationcount": 13
  },
  {
    "name": "classic rock",
    "stationcount": 720
  },
  {
    "name": "classical,classical music,classical piano,classical guitar",
    "stationcount": "1691,111,22,11"
  },
  {
    "name": "club,club dance,club house,clubbing,club dance electronic house trance",
    "stationcount": "114,60,31,32,24"
  },
  {
    "name": "college radio",
    "stationcount": 165
  },
  {
    "name": "comedy",
    "stationcount": 67
  },
  {
    "name": "commentary",
    "stationcount": 6
  },
  {
    "name": "commercial",
    "stationcount": 272
  },
  {
    "name": "community,community radio",
    "stationcount": "203,820"
  },
  {
    "name": "conservative talk",
    "stationcount": 24
  },
  {
    "name": "contemporary,contemporary hit radio",
    "stationcount": "83,24"
  },
  {
    "name": "contemporary classical",
    "stationcount": 7
  },
  {
    "name": "contemporary country",
    "stationcount": 6
  },
  {
    "name": "contemporary hits,contemporary hits radio",
    "stationcount": "167,78"
  },
  {
    "name": "contemporary jazz",
    "stationcount": 11
  },
  {
    "name": "contemporary pop rock",
    "stationcount": 9
  },
  {
    "name": "contemporary r&b,contemporary rnb",
    "stationcount": "9,6"
  },
  {
    "name": "conversation",
    "stationcount": 3
  },
  {
    "name": "cool jazz",
    "stationcount": 24
  },
  {
    "name": "country,country music,country rock,country pop,country blues",
    "stationcount": "631,47,18,15,7"
  },
  {
    "name": "culture,cultural",
    "stationcount": "283,95"
  },
  {
    "name": "cultural news",
    "stationcount": 47
  },
  {
    "name": "current affairs",
    "stationcount": 86
  },
  {
    "name": "cyberpunk",
    "stationcount": 8
  },
  {
    "name": "dance,dance 80s,dance music,dance pop",
    "stationcount": "1184,3,57,50"
  },
  {
    "name": "dancehall",
    "stationcount": 45
  },
  {
    "name": "dark",
    "stationcount": 14
  },
  {
    "name": "dark ambient",
    "stationcount": 7
  },
  {
    "name": "dark techno",
    "stationcount": 6
  },
  {
    "name": "dark wave",
    "stationcount": 8
  },
  {
    "name": "death metal",
    "stationcount": 25
  },
  {
    "name": "decades",
    "stationcount": 105
  },
  {
    "name": "deep ambient",
    "stationcount": 16
  },
  {
    "name": "deep house,deephouse",
    "stationcount": "166,10"
  },
  {
    "name": "deep techno",
    "stationcount": 12
  },
  {
    "name": "demoscene",
    "stationcount": 11
  },
  {
    "name": "disco",
    "stationcount": 274
  },
  {
    "name": "disco funk",
    "stationcount": 14
  },
  {
    "name": "drum and bass,drum & bass,dnb,drum 'n' bass,drum n bass,drum'n'bass,drum&bass",
    "stationcount": "77,36,29,18,6,9,11"
  },
  {
    "name": "documentaries",
    "stationcount": 9
  },
  {
    "name": "downtempo",
    "stationcount": 80
  },
  {
    "name": "drama",
    "stationcount": 38
  },
  {
    "name": "dream pop,dream-pop",
    "stationcount": "3,3"
  },
  {
    "name": "dub",
    "stationcount": 47
  },
  {
    "name": "dubstep",
    "stationcount": 53
  },
  {
    "name": "easy listening",
    "stationcount": 316
  },
  {
    "name": "eclectic",
    "stationcount": 206
  },
  {
    "name": "economics,economic,economy",
    "stationcount": "46,4,4"
  },
  {
    "name": "education,educational",
    "stationcount": "52,56"
  },
  {
    "name": "electro,electropop",
    "stationcount": "241,35"
  },
  {
    "name": "electro house",
    "stationcount": 42
  },
  {
    "name": "electro techno",
    "stationcount": 11
  },
  {
    "name": "electronic,elektronik,edm,electronic dance music,electronic music,electronica",
    "stationcount": "781,12,213,75,29,139"
  },
  {
    "name": "entertainment",
    "stationcount": 285
  },
  {
    "name": "ethnic",
    "stationcount": 33
  },
  {
    "name": "eurodance",
    "stationcount": 117
  },
  {
    "name": "experimental,experimental electronic music,experimental rock",
    "stationcount": "94,4,3"
  },
  {
    "name": "fantasy",
    "stationcount": 9
  },
  {
    "name": "fashion",
    "stationcount": 7
  },
  {
    "name": "female vocalists",
    "stationcount": 17
  },
  {
    "name": "festivals",
    "stationcount": 9
  },
  {
    "name": "filipino",
    "stationcount": 12
  },
  {
    "name": "finance",
    "stationcount": 6
  },
  {
    "name": "fitness",
    "stationcount": 9
  },
  {
    "name": "folk,folk music",
    "stationcount": "538,73"
  },
  {
    "name": "folk rock",
    "stationcount": 28
  },
  {
    "name": "folklore",
    "stationcount": 36
  },
  {
    "name": "freeform",
    "stationcount": 66
  },
  {
    "name": "freestyle",
    "stationcount": 9
  },
  {
    "name": "funk",
    "stationcount": 244
  },
  {
    "name": "gaming,game,games",
    "stationcount": "9,7,4"
  },
  {
    "name": "garage punk",
    "stationcount": 13
  },
  {
    "name": "garage rock",
    "stationcount": 13
  },
  {
    "name": "general",
    "stationcount": 56
  },
  {
    "name": "goldies",
    "stationcount": 52
  },
  {
    "name": "gothic",
    "stationcount": 70
  },
  {
    "name": "greek music,greek,greek folk,greek pop",
    "stationcount": "95,308,59,81"
  },
  {
    "name": "groove",
    "stationcount": 37
  },
  {
    "name": "grunge",
    "stationcount": 53
  },
  {
    "name": "grupero",
    "stationcount": 179
  },
  {
    "name": "guadalajara",
    "stationcount": 49
  },
  {
    "name": "guanajuato",
    "stationcount": 44
  },
  {
    "name": "hacker",
    "stationcount": 3
  },
  {
    "name": "hard rock",
    "stationcount": 190
  },
  {
    "name": "hard techno",
    "stationcount": 16
  },
  {
    "name": "hardcore",
    "stationcount": 65
  },
  {
    "name": "hardrock",
    "stationcount": 13
  },
  {
    "name": "hardstyle",
    "stationcount": 54
  },
  {
    "name": "hawaiian music",
    "stationcount": 7
  },
  {
    "name": "health",
    "stationcount": 18
  },
  {
    "name": "heavy metal",
    "stationcount": 157
  },
  {
    "name": "heavy rock",
    "stationcount": 22
  },
  {
    "name": "hip hop,hip-hop,hiphop",
    "stationcount": "128,149,272"
  },
  {
    "name": "hits",
    "stationcount": 1274
  },
  {
    "name": "holiday",
    "stationcount": 36
  },
  {
    "name": "hong kong",
    "stationcount": 7
  },
  {
    "name": "hot adult contemporary",
    "stationcount": 206
  },
  {
    "name": "house,house/soulful/deep house",
    "stationcount": "566,5"
  },
  {
    "name": "house techno",
    "stationcount": 8
  },
  {
    "name": "humor,humour",
    "stationcount": "25,24"
  },
  {
    "name": "idm",
    "stationcount": 19
  },
  {
    "name": "indie,indie music,indie pop,indie rock,indie dance,indie folk",
    "stationcount": "355,16,32,112,3,4"
  },
  {
    "name": "indigenous",
    "stationcount": 61
  },
  {
    "name": "industrial",
    "stationcount": 57
  },
  {
    "name": "industrial music",
    "stationcount": 3
  },
  {
    "name": "information",
    "stationcount": 505
  },
  {
    "name": "instrumental,instrumental music",
    "stationcount": "145,14"
  },
  {
    "name": "instrumental rock",
    "stationcount": 3
  },
  {
    "name": "italian",
    "stationcount": 44
  },
  {
    "name": "italian pop",
    "stationcount": 88
  },
  {
    "name": "italo disco",
    "stationcount": 56
  },
  {
    "name": "italo-disco",
    "stationcount": 4
  },
  {
    "name": "italodisco",
    "stationcount": 4
  },
  {
    "name": "j-pop,jpop,japanese idols",
    "stationcount": "19,38,9"
  },
  {
    "name": "j-rock,jrock",
    "stationcount": "9,8"
  },
  {
    "name": "japanese,japanese music",
    "stationcount": "23,13"
  },
  {
    "name": "jalisco",
    "stationcount": 66
  },
  {
    "name": "jazz,jazz music",
    "stationcount": "953,7"
  },
  {
    "name": "jazz funk",
    "stationcount": 4
  },
  {
    "name": "jazz fusion,jazz rock,jazz-rock,jazzy",
    "stationcount": "27,5,4,4"
  },
  {
    "name": "jazz lounge,jazz und lounge",
    "stationcount": "5,3"
  },
  {
    "name": "journalism",
    "stationcount": 9
  },
  {
    "name": "jungle",
    "stationcount": 33
  },
  {
    "name": "k-pop,kpop",
    "stationcount": "19,22"
  },
  {
    "name": "kids",
    "stationcount": 81
  },
  {
    "name": "languages",
    "stationcount": 5
  },
  {
    "name": "latin",
    "stationcount": 132
  },
  {
    "name": "latin music",
    "stationcount": 136
  },
  {
    "name": "latin pop,latino-pop",
    "stationcount": "218,13"
  },
  {
    "name": "latino américa",
    "stationcount": 49
  },
  {
    "name": "lifestyle",
    "stationcount": 65
  },
  {
    "name": "linux",
    "stationcount": 5
  },
  {
    "name": "liquid dnb",
    "stationcount": 7
  },
  {
    "name": "liquid funk",
    "stationcount": 7
  },
  {
    "name": "literature",
    "stationcount": 43
  },
  {
    "name": "live,livestream",
    "stationcount": "55,70"
  },
  {
    "name": "live sports",
    "stationcount": 72
  },
  {
    "name": "lo-fi,lofi,lofi hip hop",
    "stationcount": "17,29,7"
  },
  {
    "name": "local",
    "stationcount": 154
  },
  {
    "name": "local news",
    "stationcount": 567
  },
  {
    "name": "local radio",
    "stationcount": 332
  },
  {
    "name": "local talk",
    "stationcount": 60
  },
  {
    "name": "lounge,lounge music,lounge radio",
    "stationcount": "262,50,7"
  },
  {
    "name": "love,love fm,love song,love songs,lovesongs",
    "stationcount": "57,7,7,96,24"
  },
  {
    "name": "mainstream,mainstream jazz,mainstream rock",
    "stationcount": "220,8,26"
  },
  {
    "name": "malaysian pop",
    "stationcount": 7
  },
  {
    "name": "mariachi",
    "stationcount": 34
  },
  {
    "name": "meditation",
    "stationcount": 45
  },
  {
    "name": "melodic rock",
    "stationcount": 12
  },
  {
    "name": "metal,metalcore",
    "stationcount": "294,26"
  },
  {
    "name": "minimal",
    "stationcount": 61
  },
  {
    "name": "minimal techno",
    "stationcount": 32
  },
  {
    "name": "mix",
    "stationcount": 117
  },
  {
    "name": "modern",
    "stationcount": 28
  },
  {
    "name": "modern classical",
    "stationcount": 6
  },
  {
    "name": "modern rock",
    "stationcount": 28
  },
  {
    "name": "motorsport",
    "stationcount": 6
  },
  {
    "name": "movies,movie soundtracks",
    "stationcount": "18,17"
  },
  {
    "name": "multicultural",
    "stationcount": 58
  },
  {
    "name": "multimedios radio",
    "stationcount": 61
  },
  {
    "name": "música en inglés",
    "stationcount": 69
  },
  {
    "name": "nature",
    "stationcount": 18
  },
  {
    "name": "new wave",
    "stationcount": 115
  },
  {
    "name": "news",
    "stationcount": 2677
  },
  {
    "name": "news talk",
    "stationcount": 298
  },
  {
    "name": "news talk music",
    "stationcount": 50
  },
  {
    "name": "noise",
    "stationcount": 14
  },
  {
    "name": "non-commercial",
    "stationcount": 67
  },
  {
    "name": "nostalgia",
    "stationcount": 36
  },
  {
    "name": "npr",
    "stationcount": 253
  },
  {
    "name": "nu disco",
    "stationcount": 28
  },
  {
    "name": "nu metal",
    "stationcount": 15
  },
  {
    "name": "nu-jazz",
    "stationcount": 26
  },
  {
    "name": "nuevo león",
    "stationcount": 47
  },
  {
    "name": "oldies",
    "stationcount": 1120
  },
  {
    "name": "online only",
    "stationcount": 68
  },
  {
    "name": "opera",
    "stationcount": 46
  },
  {
    "name": "opm",
    "stationcount": 54
  },
  {
    "name": "orchestral,orchestra",
    "stationcount": "24,6"
  },
  {
    "name": "oriental",
    "stationcount": 7
  },
  {
    "name": "ost",
    "stationcount": 7
  },
  {
    "name": "party",
    "stationcount": 110
  },
  {
    "name": "philosophy",
    "stationcount": 5
  },
  {
    "name": "phonk",
    "stationcount": 7
  },
  {
    "name": "piano",
    "stationcount": 67
  },
  {
    "name": "piano jazz",
    "stationcount": 19
  },
  {
    "name": "pinoy",
    "stationcount": 11
  },
  {
    "name": "podcast,podcasts",
    "stationcount": "27,19"
  },
  {
    "name": "poetry",
    "stationcount": 13
  },
  {
    "name": "politics,political,political talk,politics & current affairs",
    "stationcount": "105,13,45,5"
  },
  {
    "name": "pop,pop dance,pop music,pop indie",
    "stationcount": "4707,147,764,3"
  },
  {
    "name": "pop rock,pop-rock",
    "stationcount": "532,40"
  },
  {
    "name": "popular",
    "stationcount": 195
  },
  {
    "name": "post-punk,post punk,post-hardcore",
    "stationcount": "25,7,7"
  },
  {
    "name": "post-rock",
    "stationcount": 16
  },
  {
    "name": "progressive",
    "stationcount": 69
  },
  {
    "name": "progressive house",
    "stationcount": 34
  },
  {
    "name": "progressive metal",
    "stationcount": 7
  },
  {
    "name": "progressive rock",
    "stationcount": 107
  },
  {
    "name": "progressive trance",
    "stationcount": 17
  },
  {
    "name": "psychedelic,psychedelia",
    "stationcount": "32,13"
  },
  {
    "name": "psychedelic rock",
    "stationcount": 20
  },
  {
    "name": "psychill",
    "stationcount": 8
  },
  {
    "name": "psytrance",
    "stationcount": 36
  },
  {
    "name": "public",
    "stationcount": 96
  },
  {
    "name": "public radio",
    "stationcount": 969
  },
  {
    "name": "public service",
    "stationcount": 55
  },
  {
    "name": "punk",
    "stationcount": 133
  },
  {
    "name": "punk rock",
    "stationcount": 43
  },
  {
    "name": "radio online",
    "stationcount": 69
  },
  {
    "name": "radio pública",
    "stationcount": 70
  },
  {
    "name": "rap,rap hiphop rnb",
    "stationcount": "268,50"
  },
  {
    "name": "reggae",
    "stationcount": 195
  },
  {
    "name": "reggaeton",
    "stationcount": 203
  },
  {
    "name": "regional,regional radio",
    "stationcount": "334,299"
  },
  {
    "name": "relax,relaxation,relaxation music,relaxing",
    "stationcount": "189,46,18,83"
  },
  {
    "name": "remixes",
    "stationcount": 37
  },
  {
    "name": "retro,retro music",
    "stationcount": "256,8"
  },
  {
    "name": "retro games",
    "stationcount": 10
  },
  {
    "name": "retro hits",
    "stationcount": 9
  },
  {
    "name": "retrowave",
    "stationcount": 8
  },
  {
    "name": "rhythm and blues",
    "stationcount": 29
  },
  {
    "name": "rnb,r&b,r&b soul,r&b/urban,r'n'b",
    "stationcount": "173,123,5,38,13"
  },
  {
    "name": "rock,rock 'n' roll,rock music,rock classics,rock n roll,rock'n'roll,rock ballads",
    "stationcount": "2538,19,21,24,28,30,9"
  },
  {
    "name": "romance,romantic,romantic music",
    "stationcount": "39,106,51"
  },
  {
    "name": "russian,russian hits,russian pop",
    "stationcount": "51,40,17"
  },
  {
    "name": "salsa",
    "stationcount": 214
  },
  {
    "name": "schlager",
    "stationcount": 205
  },
  {
    "name": "sci-fi",
    "stationcount": 8
  },
  {
    "name": "shoegaze",
    "stationcount": 11
  },
  {
    "name": "sinaloa",
    "stationcount": 76
  },
  {
    "name": "singer-songwriter",
    "stationcount": 48
  },
  {
    "name": "sleep",
    "stationcount": 30
  },
  {
    "name": "slow rock",
    "stationcount": 19
  },
  {
    "name": "smooth",
    "stationcount": 72
  },
  {
    "name": "smooth jazz,smoothjazz",
    "stationcount": "210,6"
  },
  {
    "name": "smooth lounge",
    "stationcount": 24
  },
  {
    "name": "football,soccer",
    "stationcount": "33,17"
  },
  {
    "name": "social",
    "stationcount": 66
  },
  {
    "name": "soft music",
    "stationcount": 33
  },
  {
    "name": "soft pop",
    "stationcount": 26
  },
  {
    "name": "soft rock",
    "stationcount": 129
  },
  {
    "name": "soul",
    "stationcount": 346
  },
  {
    "name": "soulful house",
    "stationcount": 31
  },
  {
    "name": "sounds of nature",
    "stationcount": 10
  },
  {
    "name": "soundtrack,soundtracks",
    "stationcount": "47,46"
  },
  {
    "name": "soviet",
    "stationcount": 8
  },
  {
    "name": "space,spacesynth",
    "stationcount": "18,8"
  },
  {
    "name": "spanish,spanish pop",
    "stationcount": "35,19"
  },
  {
    "name": "speech",
    "stationcount": 22
  },
  {
    "name": "spiritual",
    "stationcount": 24
  },
  {
    "name": "spoken word",
    "stationcount": 34
  },
  {
    "name": "sports,sport",
    "stationcount": "285,188"
  },
  {
    "name": "sports news",
    "stationcount": 89
  },
  {
    "name": "sports talk",
    "stationcount": 52
  },
  {
    "name": "strings",
    "stationcount": 13
  },
  {
    "name": "surf",
    "stationcount": 19
  },
  {
    "name": "surf music",
    "stationcount": 14
  },
  {
    "name": "symphonic",
    "stationcount": 13
  },
  {
    "name": "synth",
    "stationcount": 10
  },
  {
    "name": "synth-pop",
    "stationcount": 11
  },
  {
    "name": "synthpop",
    "stationcount": 44
  },
  {
    "name": "synthwave",
    "stationcount": 22
  },
  {
    "name": "tagalog",
    "stationcount": 11
  },
  {
    "name": "talk",
    "stationcount": 1406
  },
  {
    "name": "talk & speech",
    "stationcount": 233
  },
  {
    "name": "talk radio",
    "stationcount": 131
  },
  {
    "name": "talk show",
    "stationcount": 50
  },
  {
    "name": "talk show radio",
    "stationcount": 8
  },
  {
    "name": "talkshow",
    "stationcount": 12
  },
  {
    "name": "tech house",
    "stationcount": 63
  },
  {
    "name": "techno",
    "stationcount": 304
  },
  {
    "name": "technology",
    "stationcount": 13
  },
  {
    "name": "teen pop",
    "stationcount": 12
  },
  {
    "name": "thrash metal",
    "stationcount": 14
  },
  {
    "name": "top 100",
    "stationcount": 106
  },
  {
    "name": "top 40,top 40 hits,top40",
    "stationcount": "814,82,302"
  },
  {
    "name": "top charts",
    "stationcount": 126
  },
  {
    "name": "top hits",
    "stationcount": 220
  },
  {
    "name": "touhou",
    "stationcount": 5
  },
  {
    "name": "tourism",
    "stationcount": 14
  },
  {
    "name": "traditional",
    "stationcount": 55
  },
  {
    "name": "traditional country",
    "stationcount": 4
  },
  {
    "name": "traditional opera",
    "stationcount": 6
  },
  {
    "name": "traditional pop",
    "stationcount": 4
  },
  {
    "name": "traffic,traffic radio broadcast",
    "stationcount": "124,60"
  },
  {
    "name": "trance",
    "stationcount": 228
  },
  {
    "name": "trap",
    "stationcount": 65
  },
  {
    "name": "travel",
    "stationcount": 12
  },
  {
    "name": "trip hop,trip-hop,triphop",
    "stationcount": "14,19,10"
  },
  {
    "name": "tropical,tropical music",
    "stationcount": "204,42"
  },
  {
    "name": "turkish pop",
    "stationcount": 9
  },
  {
    "name": "tv",
    "stationcount": 90
  },
  {
    "name": "uk garage",
    "stationcount": 12
  },
  {
    "name": "underground",
    "stationcount": 40
  },
  {
    "name": "university",
    "stationcount": 42
  },
  {
    "name": "university radio",
    "stationcount": 213
  },
  {
    "name": "urban",
    "stationcount": 127
  },
  {
    "name": "urban contemporary",
    "stationcount": 67
  },
  {
    "name": "urbano",
    "stationcount": 72
  },
  {
    "name": "vaporwave",
    "stationcount": 16
  },
  {
    "name": "variety,variety hits",
    "stationcount": "479,57"
  },
  {
    "name": "various",
    "stationcount": 134
  },
  {
    "name": "video game,video game music,videogame music,videogames",
    "stationcount": "13,19,17,7"
  },
  {
    "name": "vocal",
    "stationcount": 29
  },
  {
    "name": "vocal house",
    "stationcount": 8
  },
  {
    "name": "vocal jazz",
    "stationcount": 33
  },
  {
    "name": "vocal trance",
    "stationcount": 10
  },
  {
    "name": "vocaloid",
    "stationcount": 8
  },
  {
    "name": "weather",
    "stationcount": 43
  },
  {
    "name": "world music",
    "stationcount": 228
  },
  {
    "name": "world news",
    "stationcount": 57
  },
  {
    "name": "youth",
    "stationcount": 74
  },
  {
    "name": "zen",
    "stationcount": 13
  }
]
```
