### ISSUE TITLE
Add station search by country

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#43]
e.g searching radio in hong kong - https://at1.api.radio-browser.info/json/stations/search?&order=random&hidebroken=true&is_https=true&countrycode=hk

Keep track of the active index when switching between "Genre" and "Country" station search filter button click
- https://react.dev/learn/sharing-state-between-components

## Tasks
- [x] Refactor slider into own component - it will be reused to show the list of countries #55 
- [x] Add "Genres" and "Countries" tab above slider
- [x] Create "Strategy" pattern classes for searching by Genre, searching by Country. Each strategy will encapsulate the `searchParams` string that will be used for searching, and the url for searching - https://refactoring.guru/design-patterns/strategy
    - [ ] Watch Strategy Pattern, The Best Software Design Pattern - Jono Williams - https://www.youtube.com/watch?v=E9-4uaoncVY 
- [x] Add search strategy to retrieve stations using countrycode
- [x] Add list of common countries to search for (100 countries sorted by total station count (desc))
- [x] Add slider component for displaying list of countries
