### ISSUE TITLE
Move map to approximate country coordinates when country filter is selected

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#57]
When country filter is selected (in the slider), move to approximate country location on the map (set zoom level if required)

**Should only perform the movement when popup is not shown!**

### Tasks
- [x] Refactor `<Map>` component to take in current lat and current lng to pan the map to. Modify that value when the country click happens AND there is no station popup currently shown!
- [x] When a station is shown, clicking on different countries in the slider should not navigate the map
- [x] Testing => Check for change in `style` applied for leaflet.js div with **`.leaflet-proxy.leaflet-zoom-animated` (use this instead, the .leaflet-map-pane is not changing in Playwright**
    -  ![image](https://github.com/user-attachments/assets/e2611d61-fa59-48ae-b07f-1e347d1c40de)

Update country list
https://worldpopulationreview.com/country-rankings/freest-countries

https://worldpopulationreview.com/country-rankings/safest-countries-in-the-world
