### ISSUE TITLE
Selection for Genre and Countries filter is not getting new stations

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#59]
The strategy loaded for "Genre" and "Countries" is not getting recreated with different offsets, causing multiple loading of new random stations to retrieve the same station

### Possible solution
Generate the random offset during the creating of the strategy `findStation` method, instead of hardcoding it in the URLSearchParams object created in the constructor
- Set the "offset" param during the `findStation` method invocation. The random number will be generated for the offset whenever the method invocation is done
- https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

# Tasks
- [x] Add test for generating two random radio stations, it should not be stuck on the first station
    - [x] Check the request url of the two requests, the offset value should be different - https://playwright.dev/docs/api/class-route#route-request
    - [x] Test for the default options selected for `Genres` and `Countries`
