### ISSUE TITLE
Create a drawer for searching a specific radio station

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#66]
Use Motion package (formerly known as framer motion) for animations - https://motion.dev/

Reference - Drawer component that is similar to https://github.com/emilkowalski/vaul OR https://mui.com/material-ui/react-drawer/

- [x] 10:45 / 19:11 Build a Drag-to-Close modal with React and Framer Motion - https://www.youtube.com/watch?v=YmDMzeL0i8M

### Tasks
- [x] #67
- [x] Create button on homepage for searching stations `Search`
    - [x] Add `selected` class and style when button is clicked
- [x] When `Search` button is clicked, a drawer is displayed from the bottom
    - [x] Drawer should be draggable to be closed (drag down by more than 100px)
    - [x] Search drawer closes when user clicks outside of the component
    - [x] Drawer closed when close icon "X" is clicked
    - [x] Animate drawer open and drawer close
- [x] Radio stations can be searched by name
- [x] #69
- [x] Each radio station displayed shows the name, bitrate, list of tags, location 
- [x] If a different search term is performed, any previous searches result list are removed

# References
- https://motion.dev/docs/react-use-drag-controls#disable-automatic-drag
- Build a Drag-to-Close modal with React and Framer Motion - https://www.youtube.com/watch?v=YmDMzeL0i8M
