### ISSUE TITLE
Create button in drawer to load more results for custom radio station search

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#71]
In drawer, display station results in groups of 10, load next 10 results only when user clicks on "Load More Results" button at the bottom of the displayed list

## Tasks
- [x] If no search for a station has been made, this button should not appear
- [x] If no more results are present, the button should be disabled. Info toast should show indicating that no more results are found
- [x] When more results are found, append those results to the existing results shown
- [x] If new station search is done with a different search criteria (e.g. different name), remove all existing search entries shown
