### ISSUE TITLE
Add favourite feature for radio station

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#89]
### Tasks
- [x] Add favourite icon to station card
    - [x] Toggle icon based on favourite state (yellow filled star icon when station is added to favourites)
        - React context changes will cause re-render of the station card on click of favourite icon (causing station card to be closed) - StationCard is using Compound Component pattern
        - In compound components, instead of passing state through props, we pass elements as children to a parent element. This allows the parent to manage the implicit state
        - Need to set the popup of Leaflet to not close on click `closeOnClick`
            - `const popup = L.popup({
      minWidth: 300,
      keepInView: true,
      closeOnClick: false,
    })` 
- [x] Save favourite list of stations using browser web storage API (local storage) - https://blog.logrocket.com/using-localstorage-react-hooks/
- [x] Allow user to view a list of favourite stations, in a drawer. When clicking on a favourite icon on the app header (beside theme switcher icon)
- [x] Allow for delete of a previous station added to favourite list. Remove immediately. The existing station card shown on the map should also have the favourite icon changed if it was unfavourited by the user
    - [x] Create a React Context for the localStorage retrieval of the favourite stations. Update the radio card whenever the context changes (using React `useEffect`)
- [x] Allow user to select a favourite station and display it on the map
