### ISSUE TITLE
Create Radio Station Player component and load onto Map as popup

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/xtal#9]
https://www.npmjs.com/package/video.js

Render radio audio component into the leaflet js Popup using React Portal - https://react.dev/reference/react-dom/createPortal#rendering-react-components-into-non-react-dom-nodes

To get the `<video>` `<source>` audio type => check the GET request's Response `Content-Type` header of the response to the `url_resolved` of the radio station. e.g. `audio/mpeg`
- Can just hardcode audio type as `audio/mpeg`

### Tasks
- [x] Create new Radio station player that will process stream url
    - [x] Create play / pause button
    - [x] Display radio station that is currently playing
    - [x] Display radio station favicon (if present)
    - [x] Display url to radio station homepage
    - [x] When radio station player component is loaded, default behavior is to not play any sound
